channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
