channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightgbm==4.3.0
  - matplotlib==3.7.5
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.1.4
  - psutil==5.9.8
  - pyarrow==15.0.2
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
