from fastapi.testclient import TestClient
from src.ocp7_scoring_model_cloud.Model_API.main import app  # make sure this points to your FastAPI app instance
import src.ocp7_scoring_model_cloud

client = TestClient(app)

def test_read_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"Hello": "World"}

def test_predict():
    # Sample input data for testing
    input_data = {"dataframe_records": [
        {
            "PREV_NAME_PAYMENT_TYPE_Noncashfromyouraccount_MEAN": "0.0",
            "AMT_GOODS_PRICE": "0.077441",
            "PREV_AMT_ANNUITY_MAX": "0.02213",
            "ORGANIZATION_TYPE_Restaurant": "0.0",
            "ORGANIZATION_TYPE_Electricity": "0.0",
            "NAME_CONTRACT_TYPE_Revolvingloans": "0.0",
            "PREV_NAME_CONTRACT_TYPE_XNA_MEAN": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Other_MEAN": "0.0",
            "NAME_HOUSING_TYPE_Coopapartment": "0.0",
            "BURO_CNT_CREDIT_PROLONG_SUM": "0.0",
            "INSTAL_DPD_SUM": "0.0",
            "APPROVED_DAYS_DECISION_MAX": "0.792879",
            "PREV_FLAG_LAST_APPL_PER_CONTRACT_Y_MEAN": "1.0",
            "ORGANIZATION_TYPE_Medicine": "0.0",
            "INSTAL_NUM_INSTALMENT_VERSION_NUNIQUE": "0.019231",
            "ORGANIZATION_TYPE_XNA": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Everydayexpenses_MEAN": "0.0",
            "PREV_CODE_REJECT_REASON_CLIENT_MEAN": "0.0",
            "WALLSMATERIAL_MODE_Panel": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_MLMpartners_MEAN": "0.0",
            "OCCUPATION_TYPE_LowskillLaborers": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Vehicles_MEAN": "1.0",
            "NAME_TYPE_SUITE_Spousepartner": "0.0",
            "PREV_APP_CREDIT_PERC_MEAN": "0.182912",
            "INSTAL_DPD_MEAN": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Autotechnology_MEAN": "1.0",
            "BURO_CREDIT_TYPE_Loanforworkingcapitalreplenishment_MEAN": "0.0",
            "WEEKDAY_APPR_PROCESS_START_SATURDAY": "0.0",
            "PREV_PRODUCT_COMBINATION_POSindustrywithinterest_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_POShouseholdwithinterest_MEAN": "0.0",
            "APPROVED_AMT_GOODS_PRICE_MEAN": "0.044211",
            "ORGANIZATION_TYPE_Agriculture": "0.0",
            "BURO_CREDIT_CURRENCY_currency4_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_AudioVideo_MEAN": "0.0",
            "POS_NAME_CONTRACT_STATUS_Returnedtothestore_MEAN": "0.0",
            "OCCUPATION_TYPE_Realtyagents": "0.0",
            "PREV_DAYS_DECISION_MEAN": "0.793151",
            "ORGANIZATION_TYPE_Industrytype6": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Businessdevelopment_MEAN": "0.0",
            "PREV_DAYS_DECISION_MIN": "0.793151",
            "BURO_DAYS_CREDIT_MIN": "0.508214",
            "PREV_NAME_CASH_LOAN_PURPOSE_Medicine_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_ConstructionMaterials_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype13": "0.0",
            "BURO_AMT_CREDIT_SUM_DEBT_MEAN": "0.025323",
            "PREV_AMT_CREDIT_MIN": "0.044211",
            "BURO_CREDIT_CURRENCY_currency1_MEAN": "1.0",
            "PREV_PRODUCT_COMBINATION_CashStreethigh_MEAN": "0.0",
            "REG_CITY_NOT_WORK_CITY": "0.0",
            "DAYS_EMPLOYED_PERC": "0.092382",
            "BURO_AMT_CREDIT_SUM_OVERDUE_MEAN": "0.0",
            "APPROVED_HOUR_APPR_PROCESS_START_MEAN": "0.391304",
            "INSTAL_DPD_MAX": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Tourism_MEAN": "0.0",
            "FONDKAPREMONT_MODE_regoperspecaccount": "0.0",
            "POS_MONTHS_BALANCE_MEAN": "0.905263",
            "PREV_NAME_GOODS_CATEGORY_DirectSales_MEAN": "0.0",
            "INSTAL_AMT_PAYMENT_MEAN": "0.004615",
            "PREV_CHANNEL_TYPE_Channelofcorporatesales_MEAN": "0.0",
            "INSTAL_PAYMENT_PERC_MAX": "0.000003",
            "ORGANIZATION_TYPE_Transporttype1": "0.0",
            "AMT_CREDIT": "0.090287",
            "ORGANIZATION_TYPE_Hotel": "0.0",
            "CNT_CHILDREN": "0.0",
            "EMERGENCYSTATE_MODE_No": "1.0",
            "INSTAL_AMT_INSTALMENT_MEAN": "0.004615",
            "ORGANIZATION_TYPE_Religion": "0.0",
            "PREV_NAME_YIELD_GROUP_middle_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Education_MEAN": "0.0",
            "NAME_FAMILY_STATUS_Separated": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Urgentneeds_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Fitness_MEAN": "0.0",
            "INSTAL_PAYMENT_PERC_MEAN": "0.000079",
            "BURO_DAYS_CREDIT_MEAN": "0.70089",
            "OBS_30_CNT_SOCIAL_CIRCLE": "0.005747",
            "NAME_TYPE_SUITE_Other_A": "0.0",
            "PREV_PRODUCT_COMBINATION_POSotherswithoutinterest_MEAN": "0.0",
            "NAME_FAMILY_STATUS_Married": "0.0",
            "PREV_NAME_CONTRACT_TYPE_Consumerloans_MEAN": "1.0",
            "ORGANIZATION_TYPE_Services": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_XNA_MEAN": "0.0",
            "BURO_AMT_CREDIT_SUM_SUM": "0.00085",
            "ORGANIZATION_TYPE_Culture": "0.0",
            "FLAG_PHONE": "1.0",
            "PREV_AMT_GOODS_PRICE_MEAN": "0.044211",
            "HOUSETYPE_MODE_blockofflats": "1.0",
            "FLAG_DOCUMENT_18": "0.0",
            "ORGANIZATION_TYPE_Police": "0.0",
            "BURO_CREDIT_ACTIVE_Closed_MEAN": "0.75",
            "WALLSMATERIAL_MODE_Mixed": "0.0",
            "POS_COUNT": "0.061224",
            "PREV_NAME_GOODS_CATEGORY_Furniture_MEAN": "0.0",
            "NAME_INCOME_TYPE_Student": "0.0",
            "ORGANIZATION_TYPE_Military": "0.0",
            "NAME_HOUSING_TYPE_Houseapartment": "1.0",
            "PREV_NAME_GOODS_CATEGORY_PhotoCinemaEquipment_MEAN": "0.0",
            "DAYS_BIRTH": "0.888839",
            "REG_REGION_NOT_LIVE_REGION": "0.0",
            "APPROVED_RATE_DOWN_PAYMENT_MAX": "0.0",
            "BURO_CREDIT_TYPE_Consumercredit_MEAN": "0.5",
            "ORGANIZATION_TYPE_Industrytype12": "0.0",
            "PREV_AMT_DOWN_PAYMENT_MEAN": "1.111111e-07",
            "PREV_WEEKDAY_APPR_PROCESS_START_THURSDAY_MEAN": "0.0",
            "PREV_AMT_DOWN_PAYMENT_MIN": "4.444442e-07",
            "PREV_NAME_CASH_LOAN_PURPOSE_Gasificationwatersupply_MEAN": "0.0",
            "REGION_POPULATION_RELATIVE": "0.256321",
            "ORGANIZATION_TYPE_Postal": "0.0",
            "PREV_AMT_CREDIT_MAX": "0.039705",
            "DEF_60_CNT_SOCIAL_CIRCLE": "0.083333",
            "NAME_FAMILY_STATUS_Civilmarriage": "0.0",
            "ORGANIZATION_TYPE_Telecom": "0.0",
            "PREV_NAME_YIELD_GROUP_low_action_MEAN": "0.0",
            "ORGANIZATION_TYPE_SecurityMinistries": "0.0",
            "ORGANIZATION_TYPE_Bank": "0.0",
            "BURO_CREDIT_TYPE_Microloan_MEAN": "0.0",
            "PREV_AMT_APPLICATION_MEAN": "0.044211",
            "ORGANIZATION_TYPE_University": "0.0",
            "BURO_CREDIT_TYPE_Loanforbusinessdevelopment_MEAN": "0.0",
            "BURO_CREDIT_TYPE_Mortgage_MEAN": "0.0",
            "WEEKDAY_APPR_PROCESS_START_WEDNESDAY": "1.0",
            "REG_CITY_NOT_LIVE_CITY": "0.0",
            "ORGANIZATION_TYPE_Government": "0.0",
            "FLAG_DOCUMENT_9": "0.0",
            "PREV_CHANNEL_TYPE_Creditandcashoffices_MEAN": "0.0",
            "APPROVED_RATE_DOWN_PAYMENT_MIN": "0.000015",
            "FONDKAPREMONT_MODE_orgspecaccount": "0.0",
            "PREV_APP_CREDIT_PERC_MAX": "0.05",
            "APPROVED_APP_CREDIT_PERC_MEAN": "0.148471",
            "INSTAL_DBD_MAX": "0.009721",
            "PREV_CODE_REJECT_REASON_XNA_MEAN": "0.0",
            "FLAG_EMAIL": "0.0",
            "PREV_NAME_CLIENT_TYPE_Refreshed_MEAN": "0.0",
            "AMT_REQ_CREDIT_BUREAU_DAY": "0.0",
            "PREV_NAME_CONTRACT_TYPE_Cashloans_MEAN": "0.0",
            "FLAG_DOCUMENT_8": "0.0",
            "INSTAL_DAYS_ENTRY_PAYMENT_MEAN": "0.898168",
            "ORGANIZATION_TYPE_Cleaning": "0.0",
            "PREV_NAME_PAYMENT_TYPE_Cashlessfromtheaccountoftheemployer_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Computers_MEAN": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Education_MEAN": "0.0",
            "WEEKDAY_APPR_PROCESS_START_TUESDAY": "0.0",
            "PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_MEAN": "0.0",
            "BURO_DAYS_CREDIT_ENDDATE_MEAN": "0.568281",
            "OCCUPATION_TYPE_Cookingstaff": "0.0",
            "PREV_NAME_CLIENT_TYPE_New_MEAN": "1.0",
            "POS_NAME_CONTRACT_STATUS_Canceled_MEAN": "0.0",
            "FLAG_DOCUMENT_3": "1.0",
            "PREV_PRODUCT_COMBINATION_CashStreetlow_MEAN": "0.0",
            "INSTAL_COUNT": "0.048518",
            "ORGANIZATION_TYPE_Security": "0.0",
            "PREV_NAME_YIELD_GROUP_XNA_MEAN": "0.0",
            "INCOME_PER_PERSON": "0.005121",
            "PREV_CODE_REJECT_REASON_LIMIT_MEAN": "0.0",
            "PREV_AMT_ANNUITY_MEAN": "0.030796",
            "INSTAL_DAYS_ENTRY_PAYMENT_SUM": "0.990053",
            "PREV_NAME_PORTFOLIO_POS_MEAN": "1.0",
            "NAME_EDUCATION_TYPE_Highereducation": "0.0",
            "AMT_REQ_CREDIT_BUREAU_QRT": "0.0",
            "PREV_NAME_PRODUCT_TYPE_XNA_MEAN": "1.0",
            "PREV_CODE_REJECT_REASON_XAP_MEAN": "1.0",
            "ORGANIZATION_TYPE_School": "0.0",
            "NAME_INCOME_TYPE_Commercialassociate": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Medicine_MEAN": "0.0",
            "CNT_FAM_MEMBERS": "0.0",
            "PREV_NAME_GOODS_CATEGORY_ConsumerElectronics_MEAN": "0.0",
            "BURO_CREDIT_TYPE_Carloan_MEAN": "0.0",
            "DAYS_REGISTRATION": "0.85214",
            "INSTAL_AMT_PAYMENT_MIN": "0.003694",
            "ORGANIZATION_TYPE_Housing": "0.0",
            "ORGANIZATION_TYPE_Tradetype6": "0.0",
            "BURO_CREDIT_TYPE_Loanforthepurchaseofequipment_MEAN": "0.0",
            "PREV_NAME_PRODUCT_TYPE_walkin_MEAN": "0.0",
            "FONDKAPREMONT_MODE_regoperaccount": "1.0",
            "REGION_RATING_CLIENT": "0.5",
            "FLAG_WORK_PHONE": "0.0",
            "ORGANIZATION_TYPE_Emergency": "0.0",
            "PREV_HOUR_APPR_PROCESS_START_MIN": "0.391304",
            "APPROVED_DAYS_DECISION_MEAN": "0.793151",
            "BURO_AMT_CREDIT_SUM_MEAN": "0.000546",
            "PREV_NAME_CASH_LOAN_PURPOSE_Journey_MEAN": "0.0",
            "APPROVED_AMT_CREDIT_MAX": "0.039705",
            "CODE_GENDER": "0.0",
            "DAYS_EMPLOYED": "0.964437",
            "APPROVED_AMT_ANNUITY_MIN": "0.030796",
            "HOUR_APPR_PROCESS_START": "0.434783",
            "NAME_HOUSING_TYPE_Municipalapartment": "0.0",
            "INSTAL_DBD_SUM": "0.036851",
            "WEEKDAY_APPR_PROCESS_START_SUNDAY": "0.0",
            "INCOME_CREDIT_PERC": "0.002338",
            "INSTAL_AMT_PAYMENT_SUM": "0.0086",
            "WALLSMATERIAL_MODE_Block": "0.0",
            "APPROVED_CNT_PAYMENT_MEAN": "0.333333",
            "NAME_HOUSING_TYPE_Withparents": "0.0",
            "PREV_NAME_PORTFOLIO_Cash_MEAN": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Consumerelectronics_MEAN": "0.0",
            "ORGANIZATION_TYPE_Tradetype2": "0.0",
            "DEF_30_CNT_SOCIAL_CIRCLE": "0.058824",
            "BURO_CREDIT_ACTIVE_Active_MEAN": "0.25",
            "PREV_PRODUCT_COMBINATION_POSindustrywithoutinterest_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Insurance_MEAN": "0.0",
            "PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN": "1.0",
            "PREV_AMT_DOWN_PAYMENT_MAX": "0.0",
            "ORGANIZATION_TYPE_BusinessEntityType1": "0.0",
            "WALLSMATERIAL_MODE_Others": "0.0",
            "OCCUPATION_TYPE_Highskilltechstaff": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Weddinggiftholiday_MEAN": "0.0",
            "PREV_NAME_CONTRACT_STATUS_Canceled_MEAN": "0.0",
            "APPROVED_AMT_GOODS_PRICE_MAX": "0.030608",
            "FLAG_MOBIL": "1.0",
            "PREV_NAME_SELLER_INDUSTRY_Clothing_MEAN": "0.0",
            "PREV_AMT_GOODS_PRICE_MIN": "0.044211",
            "ANNUITY_INCOME_PERC": "0.06491",
            "INSTAL_AMT_INSTALMENT_MAX": "0.014078",
            "POS_NAME_CONTRACT_STATUS_Approved_MEAN": "0.0",
            "PREV_CODE_REJECT_REASON_VERIF_MEAN": "0.0",
            "BURO_CREDIT_TYPE_Unknowntypeofloan_MEAN": "0.0",
            "AMT_REQ_CREDIT_BUREAU_HOUR": "0.0",
            "PREV_NAME_GOODS_CATEGORY_AutoAccessories_MEAN": "0.0",
            "PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_POSmobilewithoutinterest_MEAN": "0.0",
            "POS_MONTHS_BALANCE_SIZE": "0.061224",
            "WEEKDAY_APPR_PROCESS_START_THURSDAY": "0.0",
            "PREV_CHANNEL_TYPE_Cardealer_MEAN": "0.0",
            "POS_SK_DPD_MEAN": "0.0",
            "NAME_CONTRACT_TYPE_Cashloans": "1.0",
            "BURO_CREDIT_TYPE_Creditcard_MEAN": "0.5",
            "APPROVED_AMT_DOWN_PAYMENT_MIN": "4.444442e-07",
            "REG_REGION_NOT_WORK_REGION": "0.0",
            "EMERGENCYSTATE_MODE_Yes": "0.0",
            "OCCUPATION_TYPE_Managers": "0.0",
            "OCCUPATION_TYPE_Securitystaff": "0.0",
            "OCCUPATION_TYPE_Cleaningstaff": "0.0",
            "APPROVED_APP_CREDIT_PERC_MAX": "0.05",
            "INSTAL_PAYMENT_PERC_SUM": "0.000098",
            "NAME_FAMILY_STATUS_Singlenotmarried": "1.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Hobby_MEAN": "0.0",
            "NAME_TYPE_SUITE_Unaccompanied": "1.0",
            "PREV_NAME_TYPE_SUITE_Unaccompanied_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype5": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_XNA_MEAN": "0.0",
            "BURO_AMT_CREDIT_SUM_DEBT_SUM": "0.021165",
            "INSTAL_PAYMENT_DIFF_MEAN": "0.697823",
            "PREV_PRODUCT_COMBINATION_POShouseholdwithoutinterest_MEAN": "0.0",
            "PREV_AMT_ANNUITY_MIN": "0.030796",
            "FLAG_CONT_MOBILE": "1.0",
            "PREV_CODE_REJECT_REASON_SYSTEM_MEAN": "0.0",
            "EXT_SOURCE_2": "0.307542",
            "PREV_PRODUCT_COMBINATION_CashXSellhigh_MEAN": "0.0",
            "ORGANIZATION_TYPE_Advertising": "0.0",
            "PREV_NAME_YIELD_GROUP_high_MEAN": "0.0",
            "APPROVED_AMT_CREDIT_MEAN": "0.044211",
            "PREV_CODE_REJECT_REASON_SCO_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype2": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Repairs_MEAN": "0.0",
            "OCCUPATION_TYPE_Medicinestaff": "0.0",
            "PREV_PRODUCT_COMBINATION_CashStreetmiddle_MEAN": "0.0",
            "BURO_AMT_CREDIT_SUM_DEBT_MAX": "0.001597",
            "ORGANIZATION_TYPE_Tradetype5": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Moneyforathirdperson_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype10": "0.0",
            "PREV_NAME_GOODS_CATEGORY_OfficeAppliances_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_SportandLeisure_MEAN": "0.0",
            "PREV_NAME_TYPE_SUITE_Children_MEAN": "0.0",
            "PREV_NAME_PORTFOLIO_Cards_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_POSotherwithinterest_MEAN": "1.0",
            "NAME_INCOME_TYPE_Stateservant": "0.0",
            "PREV_NAME_CLIENT_TYPE_Repeater_MEAN": "0.0",
            "OCCUPATION_TYPE_Secretaries": "0.0",
            "PAYMENT_RATE": "0.377861",
            "PREV_NAME_GOODS_CATEGORY_AdditionalService_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_CardStreet_MEAN": "0.0",
            "LIVE_CITY_NOT_WORK_CITY": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Buyingahome_MEAN": "0.0",
            "INSTAL_DAYS_ENTRY_PAYMENT_MAX": "0.984365",
            "PREV_CHANNEL_TYPE_RegionalLocal_MEAN": "0.0",
            "PREV_NAME_TYPE_SUITE_Other_B_MEAN": "0.0",
            "PREV_CODE_REJECT_REASON_SCOFR_MEAN": "0.0",
            "BURO_AMT_CREDIT_SUM_LIMIT_SUM": "0.070253",
            "PREV_FLAG_LAST_APPL_PER_CONTRACT_N_MEAN": "0.0",
            "OCCUPATION_TYPE_Corestaff": "0.0",
            "ORGANIZATION_TYPE_Industrytype7": "0.0",
            "FLAG_OWN_REALTY": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Other_MEAN": "0.0",
            "PREV_NAME_YIELD_GROUP_low_normal_MEAN": "1.0",
            "PREV_NAME_CONTRACT_STATUS_Approved_MEAN": "1.0",
            "APPROVED_AMT_GOODS_PRICE_MIN": "0.044211",
            "FLAG_DOCUMENT_5": "0.0",
            "ORGANIZATION_TYPE_LegalServices": "0.0",
            "PREV_NAME_CONTRACT_STATUS_Refused_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_Cash_MEAN": "0.0",
            "ORGANIZATION_TYPE_Mobile": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Construction_MEAN": "0.0",
            "APPROVED_HOUR_APPR_PROCESS_START_MIN": "0.391304",
            "NAME_FAMILY_STATUS_Widow": "0.0",
            "BURO_CREDIT_DAY_OVERDUE_MEAN": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Jewelry_MEAN": "0.0",
            "PREV_CHANNEL_TYPE_Countrywide_MEAN": "0.0",
            "PREV_NAME_CONTRACT_TYPE_Revolvingloans_MEAN": "0.0",
            "BURO_CREDIT_ACTIVE_Sold_MEAN": "0.0",
            "ORGANIZATION_TYPE_Transporttype2": "0.0",
            "BURO_MONTHS_BALANCE_SIZE_SUM": "0.0414",
            "ORGANIZATION_TYPE_BusinessEntityType2": "0.0",
            "OCCUPATION_TYPE_Privateservicestaff": "0.0",
            "REGION_RATING_CLIENT_W_CITY": "0.5",
            "BURO_CREDIT_ACTIVE_Baddebt_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype8": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Furniture_MEAN": "0.0",
            "PREV_APP_CREDIT_PERC_MIN": "0.2",
            "INSTAL_PAYMENT_DIFF_VAR": "0.0",
            "ORGANIZATION_TYPE_Tradetype7": "0.0",
            "FLAG_OWN_CAR": "0.0",
            "PREV_NAME_TYPE_SUITE_Other_A_MEAN": "0.0",
            "PREV_HOUR_APPR_PROCESS_START_MEAN": "0.391304",
            "WALLSMATERIAL_MODE_Monolithic": "0.0",
            "ORGANIZATION_TYPE_Industrytype11": "0.0",
            "ORGANIZATION_TYPE_Industrytype9": "0.0",
            "ORGANIZATION_TYPE_Selfemployed": "0.0",
            "PREV_NAME_TYPE_SUITE_Spousepartner_MEAN": "0.0",
            "BURO_DAYS_CREDIT_ENDDATE_MAX": "0.583723",
            "PREV_NAME_GOODS_CATEGORY_Jewelry_MEAN": "0.0",
            "APPROVED_AMT_ANNUITY_MAX": "0.023489",
            "NAME_EDUCATION_TYPE_Lowersecondary": "0.0",
            "NAME_TYPE_SUITE_Other_B": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Industry_MEAN": "0.0",
            "FLAG_DOCUMENT_6": "0.0",
            "OCCUPATION_TYPE_Laborers": "1.0",
            "WALLSMATERIAL_MODE_Wooden": "0.0",
            "BURO_CREDIT_TYPE_Anothertypeofloan_MEAN": "0.0",
            "OCCUPATION_TYPE_HRstaff": "0.0",
            "PREV_WEEKDAY_APPR_PROCESS_START_SUNDAY_MEAN": "0.0",
            "POS_NAME_CONTRACT_STATUS_Active_MEAN": "1.0",
            "OCCUPATION_TYPE_ITstaff": "0.0",
            "ORGANIZATION_TYPE_Realtor": "0.0",
            "PREV_PRODUCT_COMBINATION_POSmobilewithinterest_MEAN": "0.0",
            "PREV_RATE_DOWN_PAYMENT_MIN": "0.000015",
            "PREV_NAME_CLIENT_TYPE_XNA_MEAN": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Buyinganewcar_MEAN": "0.0",
            "AMT_REQ_CREDIT_BUREAU_WEEK": "0.0",
            "POS_SK_DPD_DEF_MEAN": "0.0",
            "WEEKDAY_APPR_PROCESS_START_FRIDAY": "0.0",
            "APPROVED_AMT_CREDIT_MIN": "0.044211",
            "APPROVED_APP_CREDIT_PERC_MIN": "0.2",
            "WALLSMATERIAL_MODE_Stonebrick": "1.0",
            "PREV_NAME_PORTFOLIO_Cars_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_CardXSell_MEAN": "0.0",
            "ORGANIZATION_TYPE_BusinessEntityType3": "1.0",
            "PREV_NAME_GOODS_CATEGORY_Mobile_MEAN": "0.0",
            "NAME_HOUSING_TYPE_Rentedapartment": "0.0",
            "WEEKDAY_APPR_PROCESS_START_MONDAY": "0.0",
            "NAME_INCOME_TYPE_Pensioner": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Connectivity_MEAN": "0.0",
            "POS_MONTHS_BALANCE_MAX": "1.0",
            "BURO_CREDIT_TYPE_Realestateloan_MEAN": "0.0",
            "APPROVED_HOUR_APPR_PROCESS_START_MAX": "0.391304",
            "AMT_REQ_CREDIT_BUREAU_YEAR": "0.04",
            "HOUSETYPE_MODE_terracedhouse": "0.0",
            "EXT_SOURCE_3": "0.155054",
            "PREV_RATE_DOWN_PAYMENT_MEAN": "0.000008",
            "OCCUPATION_TYPE_Drivers": "0.0",
            "BURO_CREDIT_DAY_OVERDUE_MAX": "0.0",
            "PREV_CHANNEL_TYPE_APCashloan_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_CashXSelllow_MEAN": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Buyingagarage_MEAN": "0.0",
            "FLAG_DOCUMENT_4": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Buildingahouseoranannex_MEAN": "0.0",
            "NAME_INCOME_TYPE_Businessman": "0.0",
            "ORGANIZATION_TYPE_Tradetype1": "0.0",
            "PREV_CHANNEL_TYPE_Contactcenter_MEAN": "0.0",
            "PREV_PRODUCT_COMBINATION_nan_MEAN": "0.0",
            "NAME_HOUSING_TYPE_Officeapartment": "0.0",
            "ORGANIZATION_TYPE_Kindergarten": "0.0",
            "FONDKAPREMONT_MODE_notspecified": "0.0",
            "PREV_NAME_GOODS_CATEGORY_ClothingandAccessories_MEAN": "0.0",
            "INSTAL_AMT_INSTALMENT_SUM": "0.009436",
            "APPROVED_RATE_DOWN_PAYMENT_MEAN": "0.000008",
            "POS_NAME_CONTRACT_STATUS_Signed_MEAN": "0.0",
            "INSTAL_PAYMENT_PERC_VAR": "0.0",
            "PREV_AMT_CREDIT_MEAN": "0.044211",
            "PREV_NAME_CASH_LOAN_PURPOSE_Buyingaholidayhomeland_MEAN": "0.0",
            "DAYS_LAST_PHONE_CHANGE": "0.735788",
            "PREV_NAME_PORTFOLIO_XNA_MEAN": "0.0",
            "APPROVED_AMT_ANNUITY_MEAN": "0.030796",
            "DAYS_ID_PUBLISH": "0.705433",
            "PREV_NAME_PRODUCT_TYPE_xsell_MEAN": "0.0",
            "PREV_AMT_APPLICATION_MIN": "0.044211",
            "NAME_EDUCATION_TYPE_Secondarysecondaryspecial": "1.0",
            "NAME_EDUCATION_TYPE_Academicdegree": "0.0",
            "POS_SK_DPD_MAX": "0.0",
            "PREV_NAME_CONTRACT_STATUS_Unusedoffer_MEAN": "0.0",
            "APPROVED_AMT_DOWN_PAYMENT_MAX": "0.0",
            "APPROVED_DAYS_DECISION_MIN": "0.793151",
            "AMT_REQ_CREDIT_BUREAU_MON": "0.0",
            "PREV_CODE_REJECT_REASON_HC_MEAN": "0.0",
            "BURO_CREDIT_CURRENCY_currency3_MEAN": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_XAP_MEAN": "1.0",
            "PREV_NAME_GOODS_CATEGORY_Gardening_MEAN": "0.0",
            "PREV_NAME_TYPE_SUITE_Groupofpeople_MEAN": "0.0",
            "INSTAL_AMT_PAYMENT_MAX": "0.014078",
            "ORGANIZATION_TYPE_Construction": "0.0",
            "APPROVED_AMT_DOWN_PAYMENT_MEAN": "1.111111e-07",
            "AMT_INCOME_TOTAL": "0.001512",
            "INSTAL_DBD_MEAN": "0.069224",
            "PREV_NAME_TYPE_SUITE_nan_MEAN": "1.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Carrepairs_MEAN": "0.0",
            "FLAG_DOCUMENT_7": "0.0",
            "ORGANIZATION_TYPE_Transporttype3": "0.0",
            "PREV_NAME_TYPE_SUITE_Family_MEAN": "0.0",
            "OCCUPATION_TYPE_Accountants": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Refusaltonamethegoal_MEAN": "0.0",
            "FLAG_EMP_PHONE": "1.0",
            "BURO_DAYS_CREDIT_UPDATE_MEAN": "0.987737",
            "ORGANIZATION_TYPE_Industrytype3": "0.0",
            "PREV_CNT_PAYMENT_MEAN": "0.333333",
            "ORGANIZATION_TYPE_Tradetype3": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Furniture_MEAN": "0.0",
            "POS_NAME_CONTRACT_STATUS_Completed_MEAN": "0.0",
            "ORGANIZATION_TYPE_Other": "0.0",
            "HOUSETYPE_MODE_specifichousing": "0.0",
            "INSTAL_PAYMENT_DIFF_MAX": "0.015826",
            "PREV_NAME_PAYMENT_TYPE_Cashthroughthebank_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype1": "0.0",
            "NAME_INCOME_TYPE_Working": "1.0",
            "PREV_HOUR_APPR_PROCESS_START_MAX": "0.391304",
            "PREV_NAME_CASH_LOAN_PURPOSE_Paymentsonotherloans_MEAN": "0.0",
            "ORGANIZATION_TYPE_Industrytype4": "0.0",
            "POS_SK_DPD_DEF_MAX": "0.0",
            "OCCUPATION_TYPE_Waitersbarmenstaff": "0.0",
            "APPROVED_AMT_APPLICATION_MAX": "0.030608",
            "PREV_NAME_GOODS_CATEGORY_XNA_MEAN": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Buyingausedcar_MEAN": "0.0",
            "ORGANIZATION_TYPE_Transporttype4": "0.0",
            "PREV_RATE_DOWN_PAYMENT_MAX": "0.0",
            "ORGANIZATION_TYPE_Tradetype4": "0.0",
            "PREV_NAME_SELLER_INDUSTRY_Tourism_MEAN": "0.0",
            "BURO_CREDIT_TYPE_Cashloannonearmarked_MEAN": "0.0",
            "OBS_60_CNT_SOCIAL_CIRCLE": "0.005814",
            "NAME_TYPE_SUITE_Family": "0.0",
            "INSTAL_PAYMENT_DIFF_SUM": "0.59253",
            "PREV_NAME_GOODS_CATEGORY_MedicalSupplies_MEAN": "0.0",
            "LIVE_REGION_NOT_WORK_REGION": "0.0",
            "PREV_NAME_PAYMENT_TYPE_XNA_MEAN": "1.0",
            "NAME_TYPE_SUITE_Groupofpeople": "0.0",
            "BURO_DAYS_CREDIT_ENDDATE_MIN": "0.559502",
            "PREV_DAYS_DECISION_MAX": "0.792879",
            "APPROVED_AMT_APPLICATION_MIN": "0.044211",
            "PREV_PRODUCT_COMBINATION_CashXSellmiddle_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Homewares_MEAN": "0.0",
            "PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN": "0.0",
            "APPROVED_CNT_PAYMENT_SUM": "0.045455",
            "POS_NAME_CONTRACT_STATUS_Demand_MEAN": "0.0",
            "PREV_NAME_GOODS_CATEGORY_Weapon_MEAN": "0.0",
            "PREV_CHANNEL_TYPE_Stone_MEAN": "1.0",
            "POS_NAME_CONTRACT_STATUS_Amortizeddebt_MEAN": "0.0",
            "BURO_CREDIT_CURRENCY_currency2_MEAN": "0.0",
            "APPROVED_AMT_APPLICATION_MEAN": "0.044211",
            "BURO_AMT_CREDIT_SUM_MAX": "0.001136",
            "AMT_ANNUITY": "0.090032",
            "NAME_TYPE_SUITE_Children": "0.0",
            "PREV_CNT_PAYMENT_SUM": "0.013423",
            "PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN": "0.0",
            "PREV_AMT_APPLICATION_MAX": "0.030608",
            "BURO_DAYS_CREDIT_MAX": "0.96475",
            "NAME_EDUCATION_TYPE_Incompletehigher": "0.0",
            "NAME_INCOME_TYPE_Unemployed": "0.0",
            "PREV_NAME_CASH_LOAN_PURPOSE_Purchaseofelectronicequipment_MEAN": "0.0",
            "ORGANIZATION_TYPE_Insurance": "0.0",
            "PREV_AMT_GOODS_PRICE_MAX": "0.030608",
            "FLAG_DOCUMENT_11": "0.0",
            "OCCUPATION_TYPE_Salesstaff": "0.0"
        }
    ]}

    # Make a POST request to the /predict endpoint
    response = client.post("/predict", json=input_data)

    # Check the response status code
    assert response.status_code == 200

    # Check the response content
    response_json = response.json()
    assert "prediction" in response_json

    # Validate the structure of the prediction
    prediction = response_json["prediction"]
    assert isinstance(prediction, list)
    assert all(isinstance(val, list) for val in prediction)
    assert len(prediction) == len(input_data["dataframe_records"])

# def test_shap_values():
#     # Sample input data for testing
#     input_data = {"dataframe_records": [
#         {
#             "PREV_NAME_PAYMENT_TYPE_Noncashfromyouraccount_MEAN": "0.0",
#             "AMT_GOODS_PRICE": "0.077441",
#             "PREV_AMT_ANNUITY_MAX": "0.02213",
#             "ORGANIZATION_TYPE_Restaurant": "0.0",
#             "ORGANIZATION_TYPE_Electricity": "0.0",
#             "NAME_CONTRACT_TYPE_Revolvingloans": "0.0",
#             "PREV_NAME_CONTRACT_TYPE_XNA_MEAN": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Other_MEAN": "0.0",
#             "NAME_HOUSING_TYPE_Coopapartment": "0.0",
#             "BURO_CNT_CREDIT_PROLONG_SUM": "0.0",
#             "INSTAL_DPD_SUM": "0.0",
#             "APPROVED_DAYS_DECISION_MAX": "0.792879",
#             "PREV_FLAG_LAST_APPL_PER_CONTRACT_Y_MEAN": "1.0",
#             "ORGANIZATION_TYPE_Medicine": "0.0",
#             "INSTAL_NUM_INSTALMENT_VERSION_NUNIQUE": "0.019231",
#             "ORGANIZATION_TYPE_XNA": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Everydayexpenses_MEAN": "0.0",
#             "PREV_CODE_REJECT_REASON_CLIENT_MEAN": "0.0",
#             "WALLSMATERIAL_MODE_Panel": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_MLMpartners_MEAN": "0.0",
#             "OCCUPATION_TYPE_LowskillLaborers": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Vehicles_MEAN": "1.0",
#             "NAME_TYPE_SUITE_Spousepartner": "0.0",
#             "PREV_APP_CREDIT_PERC_MEAN": "0.182912",
#             "INSTAL_DPD_MEAN": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Autotechnology_MEAN": "1.0",
#             "BURO_CREDIT_TYPE_Loanforworkingcapitalreplenishment_MEAN": "0.0",
#             "WEEKDAY_APPR_PROCESS_START_SATURDAY": "0.0",
#             "PREV_PRODUCT_COMBINATION_POSindustrywithinterest_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_POShouseholdwithinterest_MEAN": "0.0",
#             "APPROVED_AMT_GOODS_PRICE_MEAN": "0.044211",
#             "ORGANIZATION_TYPE_Agriculture": "0.0",
#             "BURO_CREDIT_CURRENCY_currency4_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_AudioVideo_MEAN": "0.0",
#             "POS_NAME_CONTRACT_STATUS_Returnedtothestore_MEAN": "0.0",
#             "OCCUPATION_TYPE_Realtyagents": "0.0",
#             "PREV_DAYS_DECISION_MEAN": "0.793151",
#             "ORGANIZATION_TYPE_Industrytype6": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Businessdevelopment_MEAN": "0.0",
#             "PREV_DAYS_DECISION_MIN": "0.793151",
#             "BURO_DAYS_CREDIT_MIN": "0.508214",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Medicine_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_ConstructionMaterials_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype13": "0.0",
#             "BURO_AMT_CREDIT_SUM_DEBT_MEAN": "0.025323",
#             "PREV_AMT_CREDIT_MIN": "0.044211",
#             "BURO_CREDIT_CURRENCY_currency1_MEAN": "1.0",
#             "PREV_PRODUCT_COMBINATION_CashStreethigh_MEAN": "0.0",
#             "REG_CITY_NOT_WORK_CITY": "0.0",
#             "DAYS_EMPLOYED_PERC": "0.092382",
#             "BURO_AMT_CREDIT_SUM_OVERDUE_MEAN": "0.0",
#             "APPROVED_HOUR_APPR_PROCESS_START_MEAN": "0.391304",
#             "INSTAL_DPD_MAX": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Tourism_MEAN": "0.0",
#             "FONDKAPREMONT_MODE_regoperspecaccount": "0.0",
#             "POS_MONTHS_BALANCE_MEAN": "0.905263",
#             "PREV_NAME_GOODS_CATEGORY_DirectSales_MEAN": "0.0",
#             "INSTAL_AMT_PAYMENT_MEAN": "0.004615",
#             "PREV_CHANNEL_TYPE_Channelofcorporatesales_MEAN": "0.0",
#             "INSTAL_PAYMENT_PERC_MAX": "0.000003",
#             "ORGANIZATION_TYPE_Transporttype1": "0.0",
#             "AMT_CREDIT": "0.090287",
#             "ORGANIZATION_TYPE_Hotel": "0.0",
#             "CNT_CHILDREN": "0.0",
#             "EMERGENCYSTATE_MODE_No": "1.0",
#             "INSTAL_AMT_INSTALMENT_MEAN": "0.004615",
#             "ORGANIZATION_TYPE_Religion": "0.0",
#             "PREV_NAME_YIELD_GROUP_middle_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Education_MEAN": "0.0",
#             "NAME_FAMILY_STATUS_Separated": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Urgentneeds_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Fitness_MEAN": "0.0",
#             "INSTAL_PAYMENT_PERC_MEAN": "0.000079",
#             "BURO_DAYS_CREDIT_MEAN": "0.70089",
#             "OBS_30_CNT_SOCIAL_CIRCLE": "0.005747",
#             "NAME_TYPE_SUITE_Other_A": "0.0",
#             "PREV_PRODUCT_COMBINATION_POSotherswithoutinterest_MEAN": "0.0",
#             "NAME_FAMILY_STATUS_Married": "0.0",
#             "PREV_NAME_CONTRACT_TYPE_Consumerloans_MEAN": "1.0",
#             "ORGANIZATION_TYPE_Services": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_XNA_MEAN": "0.0",
#             "BURO_AMT_CREDIT_SUM_SUM": "0.00085",
#             "ORGANIZATION_TYPE_Culture": "0.0",
#             "FLAG_PHONE": "1.0",
#             "PREV_AMT_GOODS_PRICE_MEAN": "0.044211",
#             "HOUSETYPE_MODE_blockofflats": "1.0",
#             "FLAG_DOCUMENT_18": "0.0",
#             "ORGANIZATION_TYPE_Police": "0.0",
#             "BURO_CREDIT_ACTIVE_Closed_MEAN": "0.75",
#             "WALLSMATERIAL_MODE_Mixed": "0.0",
#             "POS_COUNT": "0.061224",
#             "PREV_NAME_GOODS_CATEGORY_Furniture_MEAN": "0.0",
#             "NAME_INCOME_TYPE_Student": "0.0",
#             "ORGANIZATION_TYPE_Military": "0.0",
#             "NAME_HOUSING_TYPE_Houseapartment": "1.0",
#             "PREV_NAME_GOODS_CATEGORY_PhotoCinemaEquipment_MEAN": "0.0",
#             "DAYS_BIRTH": "0.888839",
#             "REG_REGION_NOT_LIVE_REGION": "0.0",
#             "APPROVED_RATE_DOWN_PAYMENT_MAX": "0.0",
#             "BURO_CREDIT_TYPE_Consumercredit_MEAN": "0.5",
#             "ORGANIZATION_TYPE_Industrytype12": "0.0",
#             "PREV_AMT_DOWN_PAYMENT_MEAN": "1.111111e-07",
#             "PREV_WEEKDAY_APPR_PROCESS_START_THURSDAY_MEAN": "0.0",
#             "PREV_AMT_DOWN_PAYMENT_MIN": "4.444442e-07",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Gasificationwatersupply_MEAN": "0.0",
#             "REGION_POPULATION_RELATIVE": "0.256321",
#             "ORGANIZATION_TYPE_Postal": "0.0",
#             "PREV_AMT_CREDIT_MAX": "0.039705",
#             "DEF_60_CNT_SOCIAL_CIRCLE": "0.083333",
#             "NAME_FAMILY_STATUS_Civilmarriage": "0.0",
#             "ORGANIZATION_TYPE_Telecom": "0.0",
#             "PREV_NAME_YIELD_GROUP_low_action_MEAN": "0.0",
#             "ORGANIZATION_TYPE_SecurityMinistries": "0.0",
#             "ORGANIZATION_TYPE_Bank": "0.0",
#             "BURO_CREDIT_TYPE_Microloan_MEAN": "0.0",
#             "PREV_AMT_APPLICATION_MEAN": "0.044211",
#             "ORGANIZATION_TYPE_University": "0.0",
#             "BURO_CREDIT_TYPE_Loanforbusinessdevelopment_MEAN": "0.0",
#             "BURO_CREDIT_TYPE_Mortgage_MEAN": "0.0",
#             "WEEKDAY_APPR_PROCESS_START_WEDNESDAY": "1.0",
#             "REG_CITY_NOT_LIVE_CITY": "0.0",
#             "ORGANIZATION_TYPE_Government": "0.0",
#             "FLAG_DOCUMENT_9": "0.0",
#             "PREV_CHANNEL_TYPE_Creditandcashoffices_MEAN": "0.0",
#             "APPROVED_RATE_DOWN_PAYMENT_MIN": "0.000015",
#             "FONDKAPREMONT_MODE_orgspecaccount": "0.0",
#             "PREV_APP_CREDIT_PERC_MAX": "0.05",
#             "APPROVED_APP_CREDIT_PERC_MEAN": "0.148471",
#             "INSTAL_DBD_MAX": "0.009721",
#             "PREV_CODE_REJECT_REASON_XNA_MEAN": "0.0",
#             "FLAG_EMAIL": "0.0",
#             "PREV_NAME_CLIENT_TYPE_Refreshed_MEAN": "0.0",
#             "AMT_REQ_CREDIT_BUREAU_DAY": "0.0",
#             "PREV_NAME_CONTRACT_TYPE_Cashloans_MEAN": "0.0",
#             "FLAG_DOCUMENT_8": "0.0",
#             "INSTAL_DAYS_ENTRY_PAYMENT_MEAN": "0.898168",
#             "ORGANIZATION_TYPE_Cleaning": "0.0",
#             "PREV_NAME_PAYMENT_TYPE_Cashlessfromtheaccountoftheemployer_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Computers_MEAN": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Education_MEAN": "0.0",
#             "WEEKDAY_APPR_PROCESS_START_TUESDAY": "0.0",
#             "PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_MEAN": "0.0",
#             "BURO_DAYS_CREDIT_ENDDATE_MEAN": "0.568281",
#             "OCCUPATION_TYPE_Cookingstaff": "0.0",
#             "PREV_NAME_CLIENT_TYPE_New_MEAN": "1.0",
#             "POS_NAME_CONTRACT_STATUS_Canceled_MEAN": "0.0",
#             "FLAG_DOCUMENT_3": "1.0",
#             "PREV_PRODUCT_COMBINATION_CashStreetlow_MEAN": "0.0",
#             "INSTAL_COUNT": "0.048518",
#             "ORGANIZATION_TYPE_Security": "0.0",
#             "PREV_NAME_YIELD_GROUP_XNA_MEAN": "0.0",
#             "INCOME_PER_PERSON": "0.005121",
#             "PREV_CODE_REJECT_REASON_LIMIT_MEAN": "0.0",
#             "PREV_AMT_ANNUITY_MEAN": "0.030796",
#             "INSTAL_DAYS_ENTRY_PAYMENT_SUM": "0.990053",
#             "PREV_NAME_PORTFOLIO_POS_MEAN": "1.0",
#             "NAME_EDUCATION_TYPE_Highereducation": "0.0",
#             "AMT_REQ_CREDIT_BUREAU_QRT": "0.0",
#             "PREV_NAME_PRODUCT_TYPE_XNA_MEAN": "1.0",
#             "PREV_CODE_REJECT_REASON_XAP_MEAN": "1.0",
#             "ORGANIZATION_TYPE_School": "0.0",
#             "NAME_INCOME_TYPE_Commercialassociate": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Medicine_MEAN": "0.0",
#             "CNT_FAM_MEMBERS": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_ConsumerElectronics_MEAN": "0.0",
#             "BURO_CREDIT_TYPE_Carloan_MEAN": "0.0",
#             "DAYS_REGISTRATION": "0.85214",
#             "INSTAL_AMT_PAYMENT_MIN": "0.003694",
#             "ORGANIZATION_TYPE_Housing": "0.0",
#             "ORGANIZATION_TYPE_Tradetype6": "0.0",
#             "BURO_CREDIT_TYPE_Loanforthepurchaseofequipment_MEAN": "0.0",
#             "PREV_NAME_PRODUCT_TYPE_walkin_MEAN": "0.0",
#             "FONDKAPREMONT_MODE_regoperaccount": "1.0",
#             "REGION_RATING_CLIENT": "0.5",
#             "FLAG_WORK_PHONE": "0.0",
#             "ORGANIZATION_TYPE_Emergency": "0.0",
#             "PREV_HOUR_APPR_PROCESS_START_MIN": "0.391304",
#             "APPROVED_DAYS_DECISION_MEAN": "0.793151",
#             "BURO_AMT_CREDIT_SUM_MEAN": "0.000546",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Journey_MEAN": "0.0",
#             "APPROVED_AMT_CREDIT_MAX": "0.039705",
#             "CODE_GENDER": "0.0",
#             "DAYS_EMPLOYED": "0.964437",
#             "APPROVED_AMT_ANNUITY_MIN": "0.030796",
#             "HOUR_APPR_PROCESS_START": "0.434783",
#             "NAME_HOUSING_TYPE_Municipalapartment": "0.0",
#             "INSTAL_DBD_SUM": "0.036851",
#             "WEEKDAY_APPR_PROCESS_START_SUNDAY": "0.0",
#             "INCOME_CREDIT_PERC": "0.002338",
#             "INSTAL_AMT_PAYMENT_SUM": "0.0086",
#             "WALLSMATERIAL_MODE_Block": "0.0",
#             "APPROVED_CNT_PAYMENT_MEAN": "0.333333",
#             "NAME_HOUSING_TYPE_Withparents": "0.0",
#             "PREV_NAME_PORTFOLIO_Cash_MEAN": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Consumerelectronics_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Tradetype2": "0.0",
#             "DEF_30_CNT_SOCIAL_CIRCLE": "0.058824",
#             "BURO_CREDIT_ACTIVE_Active_MEAN": "0.25",
#             "PREV_PRODUCT_COMBINATION_POSindustrywithoutinterest_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Insurance_MEAN": "0.0",
#             "PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN": "1.0",
#             "PREV_AMT_DOWN_PAYMENT_MAX": "0.0",
#             "ORGANIZATION_TYPE_BusinessEntityType1": "0.0",
#             "WALLSMATERIAL_MODE_Others": "0.0",
#             "OCCUPATION_TYPE_Highskilltechstaff": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Weddinggiftholiday_MEAN": "0.0",
#             "PREV_NAME_CONTRACT_STATUS_Canceled_MEAN": "0.0",
#             "APPROVED_AMT_GOODS_PRICE_MAX": "0.030608",
#             "FLAG_MOBIL": "1.0",
#             "PREV_NAME_SELLER_INDUSTRY_Clothing_MEAN": "0.0",
#             "PREV_AMT_GOODS_PRICE_MIN": "0.044211",
#             "ANNUITY_INCOME_PERC": "0.06491",
#             "INSTAL_AMT_INSTALMENT_MAX": "0.014078",
#             "POS_NAME_CONTRACT_STATUS_Approved_MEAN": "0.0",
#             "PREV_CODE_REJECT_REASON_VERIF_MEAN": "0.0",
#             "BURO_CREDIT_TYPE_Unknowntypeofloan_MEAN": "0.0",
#             "AMT_REQ_CREDIT_BUREAU_HOUR": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_AutoAccessories_MEAN": "0.0",
#             "PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_POSmobilewithoutinterest_MEAN": "0.0",
#             "POS_MONTHS_BALANCE_SIZE": "0.061224",
#             "WEEKDAY_APPR_PROCESS_START_THURSDAY": "0.0",
#             "PREV_CHANNEL_TYPE_Cardealer_MEAN": "0.0",
#             "POS_SK_DPD_MEAN": "0.0",
#             "NAME_CONTRACT_TYPE_Cashloans": "1.0",
#             "BURO_CREDIT_TYPE_Creditcard_MEAN": "0.5",
#             "APPROVED_AMT_DOWN_PAYMENT_MIN": "4.444442e-07",
#             "REG_REGION_NOT_WORK_REGION": "0.0",
#             "EMERGENCYSTATE_MODE_Yes": "0.0",
#             "OCCUPATION_TYPE_Managers": "0.0",
#             "OCCUPATION_TYPE_Securitystaff": "0.0",
#             "OCCUPATION_TYPE_Cleaningstaff": "0.0",
#             "APPROVED_APP_CREDIT_PERC_MAX": "0.05",
#             "INSTAL_PAYMENT_PERC_SUM": "0.000098",
#             "NAME_FAMILY_STATUS_Singlenotmarried": "1.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Hobby_MEAN": "0.0",
#             "NAME_TYPE_SUITE_Unaccompanied": "1.0",
#             "PREV_NAME_TYPE_SUITE_Unaccompanied_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype5": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_XNA_MEAN": "0.0",
#             "BURO_AMT_CREDIT_SUM_DEBT_SUM": "0.021165",
#             "INSTAL_PAYMENT_DIFF_MEAN": "0.697823",
#             "PREV_PRODUCT_COMBINATION_POShouseholdwithoutinterest_MEAN": "0.0",
#             "PREV_AMT_ANNUITY_MIN": "0.030796",
#             "FLAG_CONT_MOBILE": "1.0",
#             "PREV_CODE_REJECT_REASON_SYSTEM_MEAN": "0.0",
#             "EXT_SOURCE_2": "0.307542",
#             "PREV_PRODUCT_COMBINATION_CashXSellhigh_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Advertising": "0.0",
#             "PREV_NAME_YIELD_GROUP_high_MEAN": "0.0",
#             "APPROVED_AMT_CREDIT_MEAN": "0.044211",
#             "PREV_CODE_REJECT_REASON_SCO_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype2": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Repairs_MEAN": "0.0",
#             "OCCUPATION_TYPE_Medicinestaff": "0.0",
#             "PREV_PRODUCT_COMBINATION_CashStreetmiddle_MEAN": "0.0",
#             "BURO_AMT_CREDIT_SUM_DEBT_MAX": "0.001597",
#             "ORGANIZATION_TYPE_Tradetype5": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Moneyforathirdperson_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype10": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_OfficeAppliances_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_SportandLeisure_MEAN": "0.0",
#             "PREV_NAME_TYPE_SUITE_Children_MEAN": "0.0",
#             "PREV_NAME_PORTFOLIO_Cards_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_POSotherwithinterest_MEAN": "1.0",
#             "NAME_INCOME_TYPE_Stateservant": "0.0",
#             "PREV_NAME_CLIENT_TYPE_Repeater_MEAN": "0.0",
#             "OCCUPATION_TYPE_Secretaries": "0.0",
#             "PAYMENT_RATE": "0.377861",
#             "PREV_NAME_GOODS_CATEGORY_AdditionalService_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_CardStreet_MEAN": "0.0",
#             "LIVE_CITY_NOT_WORK_CITY": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Buyingahome_MEAN": "0.0",
#             "INSTAL_DAYS_ENTRY_PAYMENT_MAX": "0.984365",
#             "PREV_CHANNEL_TYPE_RegionalLocal_MEAN": "0.0",
#             "PREV_NAME_TYPE_SUITE_Other_B_MEAN": "0.0",
#             "PREV_CODE_REJECT_REASON_SCOFR_MEAN": "0.0",
#             "BURO_AMT_CREDIT_SUM_LIMIT_SUM": "0.070253",
#             "PREV_FLAG_LAST_APPL_PER_CONTRACT_N_MEAN": "0.0",
#             "OCCUPATION_TYPE_Corestaff": "0.0",
#             "ORGANIZATION_TYPE_Industrytype7": "0.0",
#             "FLAG_OWN_REALTY": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Other_MEAN": "0.0",
#             "PREV_NAME_YIELD_GROUP_low_normal_MEAN": "1.0",
#             "PREV_NAME_CONTRACT_STATUS_Approved_MEAN": "1.0",
#             "APPROVED_AMT_GOODS_PRICE_MIN": "0.044211",
#             "FLAG_DOCUMENT_5": "0.0",
#             "ORGANIZATION_TYPE_LegalServices": "0.0",
#             "PREV_NAME_CONTRACT_STATUS_Refused_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_Cash_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Mobile": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Construction_MEAN": "0.0",
#             "APPROVED_HOUR_APPR_PROCESS_START_MIN": "0.391304",
#             "NAME_FAMILY_STATUS_Widow": "0.0",
#             "BURO_CREDIT_DAY_OVERDUE_MEAN": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Jewelry_MEAN": "0.0",
#             "PREV_CHANNEL_TYPE_Countrywide_MEAN": "0.0",
#             "PREV_NAME_CONTRACT_TYPE_Revolvingloans_MEAN": "0.0",
#             "BURO_CREDIT_ACTIVE_Sold_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Transporttype2": "0.0",
#             "BURO_MONTHS_BALANCE_SIZE_SUM": "0.0414",
#             "ORGANIZATION_TYPE_BusinessEntityType2": "0.0",
#             "OCCUPATION_TYPE_Privateservicestaff": "0.0",
#             "REGION_RATING_CLIENT_W_CITY": "0.5",
#             "BURO_CREDIT_ACTIVE_Baddebt_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype8": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Furniture_MEAN": "0.0",
#             "PREV_APP_CREDIT_PERC_MIN": "0.2",
#             "INSTAL_PAYMENT_DIFF_VAR": "0.0",
#             "ORGANIZATION_TYPE_Tradetype7": "0.0",
#             "FLAG_OWN_CAR": "0.0",
#             "PREV_NAME_TYPE_SUITE_Other_A_MEAN": "0.0",
#             "PREV_HOUR_APPR_PROCESS_START_MEAN": "0.391304",
#             "WALLSMATERIAL_MODE_Monolithic": "0.0",
#             "ORGANIZATION_TYPE_Industrytype11": "0.0",
#             "ORGANIZATION_TYPE_Industrytype9": "0.0",
#             "ORGANIZATION_TYPE_Selfemployed": "0.0",
#             "PREV_NAME_TYPE_SUITE_Spousepartner_MEAN": "0.0",
#             "BURO_DAYS_CREDIT_ENDDATE_MAX": "0.583723",
#             "PREV_NAME_GOODS_CATEGORY_Jewelry_MEAN": "0.0",
#             "APPROVED_AMT_ANNUITY_MAX": "0.023489",
#             "NAME_EDUCATION_TYPE_Lowersecondary": "0.0",
#             "NAME_TYPE_SUITE_Other_B": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Industry_MEAN": "0.0",
#             "FLAG_DOCUMENT_6": "0.0",
#             "OCCUPATION_TYPE_Laborers": "1.0",
#             "WALLSMATERIAL_MODE_Wooden": "0.0",
#             "BURO_CREDIT_TYPE_Anothertypeofloan_MEAN": "0.0",
#             "OCCUPATION_TYPE_HRstaff": "0.0",
#             "PREV_WEEKDAY_APPR_PROCESS_START_SUNDAY_MEAN": "0.0",
#             "POS_NAME_CONTRACT_STATUS_Active_MEAN": "1.0",
#             "OCCUPATION_TYPE_ITstaff": "0.0",
#             "ORGANIZATION_TYPE_Realtor": "0.0",
#             "PREV_PRODUCT_COMBINATION_POSmobilewithinterest_MEAN": "0.0",
#             "PREV_RATE_DOWN_PAYMENT_MIN": "0.000015",
#             "PREV_NAME_CLIENT_TYPE_XNA_MEAN": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Buyinganewcar_MEAN": "0.0",
#             "AMT_REQ_CREDIT_BUREAU_WEEK": "0.0",
#             "POS_SK_DPD_DEF_MEAN": "0.0",
#             "WEEKDAY_APPR_PROCESS_START_FRIDAY": "0.0",
#             "APPROVED_AMT_CREDIT_MIN": "0.044211",
#             "APPROVED_APP_CREDIT_PERC_MIN": "0.2",
#             "WALLSMATERIAL_MODE_Stonebrick": "1.0",
#             "PREV_NAME_PORTFOLIO_Cars_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_CardXSell_MEAN": "0.0",
#             "ORGANIZATION_TYPE_BusinessEntityType3": "1.0",
#             "PREV_NAME_GOODS_CATEGORY_Mobile_MEAN": "0.0",
#             "NAME_HOUSING_TYPE_Rentedapartment": "0.0",
#             "WEEKDAY_APPR_PROCESS_START_MONDAY": "0.0",
#             "NAME_INCOME_TYPE_Pensioner": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Connectivity_MEAN": "0.0",
#             "POS_MONTHS_BALANCE_MAX": "1.0",
#             "BURO_CREDIT_TYPE_Realestateloan_MEAN": "0.0",
#             "APPROVED_HOUR_APPR_PROCESS_START_MAX": "0.391304",
#             "AMT_REQ_CREDIT_BUREAU_YEAR": "0.04",
#             "HOUSETYPE_MODE_terracedhouse": "0.0",
#             "EXT_SOURCE_3": "0.155054",
#             "PREV_RATE_DOWN_PAYMENT_MEAN": "0.000008",
#             "OCCUPATION_TYPE_Drivers": "0.0",
#             "BURO_CREDIT_DAY_OVERDUE_MAX": "0.0",
#             "PREV_CHANNEL_TYPE_APCashloan_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_CashXSelllow_MEAN": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Buyingagarage_MEAN": "0.0",
#             "FLAG_DOCUMENT_4": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Buildingahouseoranannex_MEAN": "0.0",
#             "NAME_INCOME_TYPE_Businessman": "0.0",
#             "ORGANIZATION_TYPE_Tradetype1": "0.0",
#             "PREV_CHANNEL_TYPE_Contactcenter_MEAN": "0.0",
#             "PREV_PRODUCT_COMBINATION_nan_MEAN": "0.0",
#             "NAME_HOUSING_TYPE_Officeapartment": "0.0",
#             "ORGANIZATION_TYPE_Kindergarten": "0.0",
#             "FONDKAPREMONT_MODE_notspecified": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_ClothingandAccessories_MEAN": "0.0",
#             "INSTAL_AMT_INSTALMENT_SUM": "0.009436",
#             "APPROVED_RATE_DOWN_PAYMENT_MEAN": "0.000008",
#             "POS_NAME_CONTRACT_STATUS_Signed_MEAN": "0.0",
#             "INSTAL_PAYMENT_PERC_VAR": "0.0",
#             "PREV_AMT_CREDIT_MEAN": "0.044211",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Buyingaholidayhomeland_MEAN": "0.0",
#             "DAYS_LAST_PHONE_CHANGE": "0.735788",
#             "PREV_NAME_PORTFOLIO_XNA_MEAN": "0.0",
#             "APPROVED_AMT_ANNUITY_MEAN": "0.030796",
#             "DAYS_ID_PUBLISH": "0.705433",
#             "PREV_NAME_PRODUCT_TYPE_xsell_MEAN": "0.0",
#             "PREV_AMT_APPLICATION_MIN": "0.044211",
#             "NAME_EDUCATION_TYPE_Secondarysecondaryspecial": "1.0",
#             "NAME_EDUCATION_TYPE_Academicdegree": "0.0",
#             "POS_SK_DPD_MAX": "0.0",
#             "PREV_NAME_CONTRACT_STATUS_Unusedoffer_MEAN": "0.0",
#             "APPROVED_AMT_DOWN_PAYMENT_MAX": "0.0",
#             "APPROVED_DAYS_DECISION_MIN": "0.793151",
#             "AMT_REQ_CREDIT_BUREAU_MON": "0.0",
#             "PREV_CODE_REJECT_REASON_HC_MEAN": "0.0",
#             "BURO_CREDIT_CURRENCY_currency3_MEAN": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_XAP_MEAN": "1.0",
#             "PREV_NAME_GOODS_CATEGORY_Gardening_MEAN": "0.0",
#             "PREV_NAME_TYPE_SUITE_Groupofpeople_MEAN": "0.0",
#             "INSTAL_AMT_PAYMENT_MAX": "0.014078",
#             "ORGANIZATION_TYPE_Construction": "0.0",
#             "APPROVED_AMT_DOWN_PAYMENT_MEAN": "1.111111e-07",
#             "AMT_INCOME_TOTAL": "0.001512",
#             "INSTAL_DBD_MEAN": "0.069224",
#             "PREV_NAME_TYPE_SUITE_nan_MEAN": "1.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Carrepairs_MEAN": "0.0",
#             "FLAG_DOCUMENT_7": "0.0",
#             "ORGANIZATION_TYPE_Transporttype3": "0.0",
#             "PREV_NAME_TYPE_SUITE_Family_MEAN": "0.0",
#             "OCCUPATION_TYPE_Accountants": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Refusaltonamethegoal_MEAN": "0.0",
#             "FLAG_EMP_PHONE": "1.0",
#             "BURO_DAYS_CREDIT_UPDATE_MEAN": "0.987737",
#             "ORGANIZATION_TYPE_Industrytype3": "0.0",
#             "PREV_CNT_PAYMENT_MEAN": "0.333333",
#             "ORGANIZATION_TYPE_Tradetype3": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Furniture_MEAN": "0.0",
#             "POS_NAME_CONTRACT_STATUS_Completed_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Other": "0.0",
#             "HOUSETYPE_MODE_specifichousing": "0.0",
#             "INSTAL_PAYMENT_DIFF_MAX": "0.015826",
#             "PREV_NAME_PAYMENT_TYPE_Cashthroughthebank_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype1": "0.0",
#             "NAME_INCOME_TYPE_Working": "1.0",
#             "PREV_HOUR_APPR_PROCESS_START_MAX": "0.391304",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Paymentsonotherloans_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Industrytype4": "0.0",
#             "POS_SK_DPD_DEF_MAX": "0.0",
#             "OCCUPATION_TYPE_Waitersbarmenstaff": "0.0",
#             "APPROVED_AMT_APPLICATION_MAX": "0.030608",
#             "PREV_NAME_GOODS_CATEGORY_XNA_MEAN": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Buyingausedcar_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Transporttype4": "0.0",
#             "PREV_RATE_DOWN_PAYMENT_MAX": "0.0",
#             "ORGANIZATION_TYPE_Tradetype4": "0.0",
#             "PREV_NAME_SELLER_INDUSTRY_Tourism_MEAN": "0.0",
#             "BURO_CREDIT_TYPE_Cashloannonearmarked_MEAN": "0.0",
#             "OBS_60_CNT_SOCIAL_CIRCLE": "0.005814",
#             "NAME_TYPE_SUITE_Family": "0.0",
#             "INSTAL_PAYMENT_DIFF_SUM": "0.59253",
#             "PREV_NAME_GOODS_CATEGORY_MedicalSupplies_MEAN": "0.0",
#             "LIVE_REGION_NOT_WORK_REGION": "0.0",
#             "PREV_NAME_PAYMENT_TYPE_XNA_MEAN": "1.0",
#             "NAME_TYPE_SUITE_Groupofpeople": "0.0",
#             "BURO_DAYS_CREDIT_ENDDATE_MIN": "0.559502",
#             "PREV_DAYS_DECISION_MAX": "0.792879",
#             "APPROVED_AMT_APPLICATION_MIN": "0.044211",
#             "PREV_PRODUCT_COMBINATION_CashXSellmiddle_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Homewares_MEAN": "0.0",
#             "PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN": "0.0",
#             "APPROVED_CNT_PAYMENT_SUM": "0.045455",
#             "POS_NAME_CONTRACT_STATUS_Demand_MEAN": "0.0",
#             "PREV_NAME_GOODS_CATEGORY_Weapon_MEAN": "0.0",
#             "PREV_CHANNEL_TYPE_Stone_MEAN": "1.0",
#             "POS_NAME_CONTRACT_STATUS_Amortizeddebt_MEAN": "0.0",
#             "BURO_CREDIT_CURRENCY_currency2_MEAN": "0.0",
#             "APPROVED_AMT_APPLICATION_MEAN": "0.044211",
#             "BURO_AMT_CREDIT_SUM_MAX": "0.001136",
#             "AMT_ANNUITY": "0.090032",
#             "NAME_TYPE_SUITE_Children": "0.0",
#             "PREV_CNT_PAYMENT_SUM": "0.013423",
#             "PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN": "0.0",
#             "PREV_AMT_APPLICATION_MAX": "0.030608",
#             "BURO_DAYS_CREDIT_MAX": "0.96475",
#             "NAME_EDUCATION_TYPE_Incompletehigher": "0.0",
#             "NAME_INCOME_TYPE_Unemployed": "0.0",
#             "PREV_NAME_CASH_LOAN_PURPOSE_Purchaseofelectronicequipment_MEAN": "0.0",
#             "ORGANIZATION_TYPE_Insurance": "0.0",
#             "PREV_AMT_GOODS_PRICE_MAX": "0.030608",
#             "FLAG_DOCUMENT_11": "0.0",
#             "OCCUPATION_TYPE_Salesstaff": "0.0"
#         }
#     ]}
#     # Make a POST request to the /explain_local endpoint
#     response = client.post("/explain_local", json=input_data)
#
#     # Check the response status code
#     assert response.status_code == 200
#
#     # Check the response content
#     response_json = response.json()
#     assert "shap_values" in response_json
#
#     # Validate the structure of the shap_values
#     shap_values = response_json["shap_values"]
#     assert isinstance(shap_values, list)
#     assert all(isinstance(val, list) for val in shap_values)
#     assert len(shap_values) == len(input_data["dataframe_records"])
