name: Azure WebApp Model API CI/CD

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version your app uses

    - name: Install dependencies
      run: |
        cd ./src/ocp7_scoring_model_cloud/Model_API
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd /
        pytest  # Adjust this if you use a different test framework

    - name: Deploy Model API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ocp7-rlhk-modelapi  # Replace with your Azure Web App name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./src/ocp7_scoring_model_cloud/Model_API  # Path to your application folder
