name: Python CI

on:
  push:

env:
  AZURE_WEBAPP_NAME: ocp7mdlprod # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow requests pytest && pip install -r ./notebooks/production_model/requirements.txt
    - name: Build and package web app
      run: |
        # Create a startup script for the MLflow server
        echo "nohup mlflow models serve -m ./mlruns/production_model -h 0.0.0.0 -p 5000 &" > start_mlflow.sh
        chmod +x start_mlflow.sh
        # Archive the web app for deployment
        zip -r app.zip ./*
    - name: Deploy web app using azure/webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.zip
    - name: Start MLflow server on Azure
      run: |
        ssh azureuser@${{ secrets.AZURE_WEBAPP_HOST }} "bash -s" < ./start_mlflow.sh
