name: build_docker_production_model_api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              pip install mlflow requests pytest && pip install -r ./notebooks/production_model/requirements.txt

          - name: Serve MLflow model
            run: |
              mlflow models serve -m ./notebooks/production_model --env-manager local -p 5000 &
              sleep 20  # Wait for the model to be served

          - name: Run tests
            run: pytest /tests/test_production_model_api.py

          - name: Stop MLflow server
            run: |
              pkill -f 'mlflow'