#name: build_docker_production_model_api
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#    build:
#        runs-on: ubuntu-latest
#        steps:
#          - name: Checkout code
#            uses: actions/checkout@v2
#
#          - name: Set up Python
#            uses: actions/setup-python@v2
#            with:
#              python-version: '3.10'
#
#          - name: Install dependencies
#            run: |
#              pip install mlflow requests pytest && pip install -r ./notebooks/production_model/requirements.txt
#
#          - name: Deploy to PythonAnywhere
#            env:
#              PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
#            run: |
#              pip install pythonanywhere
#              pa_autoconfigure_webapp robinlhl.pythonanywhere.com --python=3.10
#              # The above command is an example; adapt it according to your Python version and web app configuration
#
#          - name: Copy files to PythonAnywhere
#            env:
#              PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
#            run: |
#              pa_upload_webapp robinlhl.pythonanywhere.com --source-directory . --target-directory ~/<your_target_directory>/